version: '3.9'
services:
  # database section
  #productdb: mysql 
  productdb: 
    container_name: productdb
    environment:
        MYSQL_ROOT_PASSWORD: Password!
        MYSQL_USER: root
        MYSQL_PASSWORD: Password!
        MYSQL_DATABASE: aspnetcore-microservices
        restart: always
    volumes: 
        - mysql_data:/var/lib/mysql
    expose:
        - "3306"
  #customerdb: postgres 
  customerdb: 
    container_name: postgresdb
    environment: 
        - POSTGRES USER=admin 
        - POSTGRES PASSWORD=admin1234 
        - POSTGRES_DB=DiscountDb
    restart: always
    ports: 
        - "5433:5432"
    volumes: 
        - postgres_data:/var/lib/postgresql/data
#basketdb: 
  basketdb:
    container_name: basketdb
    restart: always 
    ports: 
        - "6379:6379" 
#inventorydb: mongo 
  inventorydb: 
    container_name: inventorydb
    restart: always
    ports: 
        - "27017:27017"
    volumes: 
        - mongo_data:/data/db 
#infrastructure section 
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports: 
        - "5672:5672" 
        - "15672:15672"
#page admin
  pgadmin:
    container_name: pgadmin
    environment: 
        - PGADMIN_DEFAULT_EMAIL=admin@tedu_microservice.com 
        - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports: 
        - "5050:80" 
    volumes: 
        - pgadmin_data:/root/.pgadmin 
  portainer:
    container_name: portainer
    restart: always
    ports: 
        - "8080:8000" 
        - "9088:9000"
    volumes: 
        - /var/run/docker.sock:/var/run/docker.sock portainer_data:/data

  elasticsearch:
    container_name: elasticsearch
    environment: 
        - xpack.monitoring.enabled=true 
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node 
    ports: 
        - "9200:9200" 
    volumes: 
        - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment: 
        - ELASTICSEARCH_URL=http://elasticsearch:9200 
    depends_on: 
        - elasticsearch 
    ports: 
        - "5601:5601"
  
  product.api:
     container_name: product.api
     environment:
        - ASPNETCORE_ENVIROMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - "ConnectionStrings: DefaultConnectionString=Server=localhost;Port=3306;Database=aspnetcore-microservices;Uid=root;Pwd=Password!;"
     depends_on:
        - productdb
     ports:
        - "6002:80"
     restart: always