version: '3.9'
services:
  # database section
  #sqlserverdb:
  #  image: mcr.microsoft.com/mssql/server:2019-latest
  mysqldb:
    image: mysql:8.0.29
  #orderdb:
  #  image: mcr.microsoft.com/mssql/server:2019-latest
  productdb:
    image: mysql:8.0.29
  customerdb:
    image: postgres:alpine3.16
  basketdb:
    image: redis:alpine
  #inventorydb: 
  #  image: mongo
  # #infrastructure section
  #rabbitmq:
  #  image: rabbitmq:3-management-alpine
  pgadmin:
    image: dpage/pgadmin4 
  #portainer:
  #  image: portainer/portainer-ce 
  #elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
  #kibana:
    #image: docker.elastic.co/kibana/kibana:7.17.2
  product.api:
     image: productapi:runtime
     build:
       context: .
       dockerfile: src/Services/Product.API/Dockerfile
   
  customer.api:
     image: customerapi:runtime
     build:
       context: .
       dockerfile: src/Services/Customer.API/Dockerfile
  basket.api:
     image: basketapi:runtime
     build:
       context: .
       dockerfile: src/Services/Basket.API/Dockerfile
#microservices
networks:
  default:
    name: aspnetcore-microservices
    external: true
    driver: bridge
volumes:
  mysql_data:
#volumes:
#  #sqlserver_data:
#  #  name: sqlserver_data
#  mysql_data:
#    name: dbdata
  postgres_data:
  #portainer_data:
  #  name: portainer_data
  #elasticsearch_data:
  #  name: elasticsearch_data
  #jaeger_data: 
  #  name: jaeger_data
  #mongo_data:
  #  name: mongo_data
  pgadmin_data: